project:
  type: website
  output-dir: docs

website:
  title: "All sorts of GitHub guides"
  description: "test site"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "GitHub Guides"
        contents:
          - 1-first-repo.qmd
          - 3-version-control.qmd
	    - 4-databricks-github.qmd
      - section: "Principles
        contents:
          - 2-understanding-code.qmd
      - section: "Placeholder"
	  contents:
          - N-another-page.qmd
      
format:
  html:
    toc: true
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
