project:
  type: website
  output-dir: docs

website:
  title: "SE D&A GitHub Guides"
  description: "test site"
  sidebar:
    foreground: "black"
    background: "#EBF5FF"
    style: "docked"
    search: true
    contents:
      - section: "GitHub Guides"
        contents:
          - 1-first-repo.qmd
          - 3a-r-studio.qmd
          - 3b-vs-code.qmd
          - 4-databricks-github.qmd
      - section: "Principles"
        contents:
          - 2-understanding-code.qmd
      - section: "Placeholder"
        contents:
          - N-another-page.qmd
      
format:
  html:
    toc: true
    css: styles.css

execute:
  freeze: auto
