project:
  type: website
  output-dir: docs

website:
  title: "All sorts of GitHub guides"
  description: "test site"

  navbar:
    background: light
    title: false
    collapse-below: lg
    search: true
    left:
      - text: "Your first ever repo"
        href: 1-first-repo.qmd
      - text: "Making sense of code"
        href: 2-understanding-code.qmd 
      - text: "Version Control"
        href: 3-version-control.qmd   
      - text: "GitHub in Databricks"
        href: 4-databricks-github.qmd      
      - text: "Another Page"
        href: N-another-page.qmd
      # - text: "Updates"
      #   icon: "rss"
      #   href: updates.qmd
      
format:
  html:
    toc: true
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
